### ISSUE TITLE
New release and tag required?

### ISSUE THREAD

**Issue by durack1** [p7zip-project/p7zip#129]
This is great, thanks for forking and updating the [p7zip sourceforge repo](https://sourceforge.net/projects/p7zip/files/p7zip/)!

Just wondering if a new release tag is required, you've noted v19.00 in https://github.com/jinfeihan57/p7zip/commit/6106df26ff64fa8147bfc9abdc0a14908b5d3871, but it seems that [17.03](https://github.com/jinfeihan57/p7zip/releases) is the latest tagged release.

I also wonder if a refresh using the 7-zip [21.01](https://sourceforge.net/p/sevenzip/discussion/45797/thread/cec5e63147/) release source would be useful, or possible? It seems this was updated on 10th March 2021, so should be up-to-date

**Comment by jo620kix** [comment]
Although I am **not** a maintainer or contributor of this fork...

>  noted v19.00 in 6106df2

I think this fork is mainly based on 7-Zip 17.00 / 17.01. Most of the code are not updated to 19.00 yet.

> I also wonder if a refresh using the 7-zip 21.01 release source would be useful, or possible?

Igor Pavlov has yet to release the source code of 21.01. :(

21.01 is an alpha version, and Igor Pavlov said "the source code of new version and another additional packages will be released later after some testing period".

If you really want to try 21.01, Igor Pavlov provides a [Linux version](https://sourceforge.net/p/sevenzip/discussion/45797/thread/d401ab2966/), but as mentioned above, the source code is not available so you can only use the binary executable.

**Comment by jo620kix** [comment]
It seems that [7zz can be run on CentOS 8.3.2011](https://sourceforge.net/p/sevenzip/discussion/45797/thread/cec5e63147/?page=3&limit=25#8e6f).

Regarding the future of this repo, [the owner (jinfeihan57) said](https://github.com/jinfeihan57/p7zip/issues/114#issuecomment-796833759):
> This is definitely a GOOD news.
> Now we just need to wait for the source code of 7zip-21.0 to be released. According to the source code, we can decide how to develop the next step.

**Comment by jinfeihan57** [comment]
Originally there was a plan to release 19.00, but the author of 7zip has released 21.00 and supports some linux systems.  This disrupted my own plans.  The plan now is to wait for the author to release the source code of version 21.00 and make a new plan.  Otherwise, if I put too much effort on 19.00, it will delay the update of p7zip 21.00. 😄

**Comment by tansy** [comment]
> if I put too much effort on 19.00, it will delay the update of p7zip 21.00. 😄

I don't think he (Pavlov) will release it soon as he did not release version 20 yet. Not to mention 21.

He said 
> It's possible to merge 7-Zip code with p7zip compiler scripts.
Whatever that means from him, but IMO "merging" lzma-19-sdk would be good idea, it's most likely much less buggy than version 16 or 17 for that matter.

**Comment by jo620kix** [comment]
3 days ago, [Pavlov said](https://sourceforge.net/p/sevenzip/discussion/45797/thread/d401ab2966/#fe87/9b19):
> It's alpha version with "delayed" source release.
> The source will be released in several weeks.

I believe Pavlov will keep his promise - in August last year, [he said](https://sourceforge.net/p/sevenzip/discussion/45797/thread/7d5b1e5b51/#0a38/e51a/a3c6/9b39/fc87/d7e7/1d20) he plans to work for linux version of 7-Zip more in near future. Then the Linux version is released on March.

If the source is not released in 1-2 months, perhaps we can remind him again...

**Comment by wdlkmpx** [comment]
Yes, a new relase is required:
- update zstd and probably other files
- merge the lzip PR
-  release 17.04

wait for the new secret code, ditch all the changes and start redoing everything again

**Comment by wdlkmpx** [comment]
I bet some work went into making things work with the current p7zip, due to uncertainty, it would be wise to create a new branch named 17.00:

- git checkout v17.01
- git checkout -b 17.00
- git merge master
- git push upstream 17.00

That way the 17.00 version can be maintained with bug fixes and point releases, and the development can continue in the master branch, with a different codebase perhaps.

**Comment by tansy** [comment]
> The source will be released in several weeks.

Sorry to say it but I don't buy it.

Quote:
> It's possible to merge 7-Zip code with p7zip compiler scripts.
> But I don't work with Linux. So it's difficult for me to maintain all these Linux scripting and packaging things from p7zip.

**But I don't work with Linux**...

He repeats that ad nauseam. And even blames p7zip developer, who dropped project few years ago.

The thing is, the whole project is written for windows, "in windows"  (I mean in visual studio, using windows data types and all that stuff, which makes it very, very difficult to port. That's the reason, everyone left this project - it was tiresome to change thousands of lines manually every single release.
And for years and years of disregarding effort of many linux users and programmers who brought immense number of fixes and found countless number of bugs people fed up and rightly so.

Fact that recently many new projects got interested again is not thank to authors efforts but rather despite of them.

**Comment by jinfeihan57** [comment]
> 3 days ago, [Pavlov said](https://sourceforge.net/p/sevenzip/discussion/45797/thread/d401ab2966/#fe87/9b19):
> 
> > It's alpha version with "delayed" source release.
> > The source will be released in several weeks.
> 
> I believe Pavlov will keep his promise - in August last year, [he said](https://sourceforge.net/p/sevenzip/discussion/45797/thread/7d5b1e5b51/#0a38/e51a/a3c6/9b39/fc87/d7e7/1d20) he plans to work for linux version of 7-Zip more in near future. Then the Linux version is released on March.
> 
> If the source is not released in 1-2 months, perhaps we can remind him again...

Yes, we should be more patient. After all this is a big project.

**Comment by teoberi** [comment]
Release 17.04 but the program version remained 17.03?

**Comment by jinfeihan57** [comment]
Released new version 17.04.

**Comment by teoberi** [comment]
OK!
I still don't know when 7-Zip for Linux will appear, what I will choose between the two variants!

**Comment by JpegXguy** [comment]
Source code release https://sourceforge.net/p/sevenzip/discussion/45797/thread/7fe6c21efa/
Next steps?

**Comment by jinfeihan57** [comment]
@JpegXguy I test [7z21.02 src code](https://7-zip.org/a/7z2102-src.7z) on red-hat 7.6 using gcc_4.8.5 g++_4.8.5. it need little changes to compile 7za.
cd CPP/7zip/Bundles/Alone
make -f makefile.gcc

**Comment by jo620kix** [comment]
If anyone wants to try extracting 7z and zip archives which use Zstd in Linux using 7-Zip 21.02, try [this repo's zstd branch](https://gitlab.com/v4kvoi6pcbmv/7-zip/-/tree/zstd).

#### Compilation
| Binary | Path                       | Output dir (Non-ASM)            | Output dir (ASM)                    |
|--------|----------------------------|---------------------------------|-------------------------------------|
| 7z     | CPP/7zip/UI/Console        | CPP/7zip/UI/Console/b/g/        | CPP/7zip/UI/Console/b/g_x64/        |
| 7z.so  | CPP/7zip/Bundles/Format7zF | CPP/7zip/Bundles/Format7zF/b/g/ | CPP/7zip/Bundles/Format7zF/b/g_x64/ |
| 7za    | CPP/7zip/Bundles/Alone     | CPP/7zip/Bundles/Alone/b/g/     | CPP/7zip/Bundles/Alone/b/g_x64/     |
| 7zr    | CPP/7zip/Bundles/Alone7z   | CPP/7zip/Bundles/Alone7z/b/g/   | CPP/7zip/Bundles/Alone7z/b/g_x64/   |

Non-ASM build (assembler code not used):
1. Checkout the `zstd` branch and the submodule (`extra-codecs`)
2. `sed -i 's|CFLAGS_WARN_WALL = -Wall -Werror -Wextra|CFLAGS_WARN_WALL = -Wall -Wextra|g' CPP/7zip/7zip_gcc.mak`
3. `cd` to the respective path and run `make -f ../../cmpl_gcc.mak`. Repeat this step for other binaries that you need.
4. The output is available under the respective output directory.

ASM build (assembler code is used):
1. Build `uasm` from [this branch (2.50)](https://github.com/Terraspace/UASM/tree/v2.50) or [this repo (2.51.2)](https://github.com/Navegos/UASM).
2. Checkout the `zstd` branch and the submodule (`extra-codecs`)
3. `sed -i 's|CFLAGS_WARN_WALL = -Wall -Werror -Wextra|CFLAGS_WARN_WALL = -Wall -Wextra|g' CPP/7zip/7zip_gcc.mak`
4. `sed -i 's|MY_ASM = asmc|MY_ASM = uasm|g' CPP/7zip/7zip_gcc.mak`
5. `cd` to the respective path and run `make -f ../../cmpl_gcc_x64.mak`. Repeat this step for other binaries that you need.
4. The output is available under the respective output directory.

#### Notes
1. Only Linux is supported (only the Makefiles for Linux are patched).
2. Only Zstd support in 7z and ZIP has been added.
3. To use Zstd when creating a ZIP archive, use `zstd-wz`.
4. For Zstd in ZIP, both method IDs (20 and 93) are supported for decompression. ([Sample file](https://github.com/mcmilk/7-Zip-zstd/files/6383455/zstdzip.zip) using the deprecated ID 20 by @klauspost)

**Comment by stefano2734** [comment]
Is there a new plan for a release in 2022?

**Comment by jpegxguy** [comment]
@jinfeihan57 Is this completed? In what way?
a) New release for this project or
b) Continue with official implementation from 7-Zip's maintainer

?
