### ISSUE TITLE
hashing (7z h) fails with 'Unknown Error'

### ISSUE THREAD

**Issue by tansy** [p7zip-project/p7zip#145]
I discoverd weird behaviour of hashing command - last master _7z_ fails with _Unknown Error_; _7za_ works. At first I thought it's me as I tried to move mentioned in #141 codecs to _Codecs_ directory but it turned out not to be the case. Also released on 4/04 version 17.04 works fine so it had to be done in between.

Last master:

```
/mnt/dev1/dev/src/pak/7zip/p7zip/p7zip-master-2021.05.18/bin $ ./7za h 7z

7-Zip (a) [32] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=pl_PL.utf8,Utf16=on,HugeFiles=on,32 bits,2 CPUs x86)

Scanning
1 file, 687205 bytes (672 KiB)

CRC32             Size  Name
-------- -------------  ------------
257917A1        687205  7z
-------- -------------  ------------
257917A1        687205  

Size: 687205

CRC32  for data:              257917A1

Everything is Ok
```

```
/mnt/dev1/dev/src/pak/7zip/p7zip/p7zip-master-2021.05.18/bin $ ./7z h 7z

7-Zip [32] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=pl_PL.utf8,Utf16=on,HugeFiles=on,32 bits,2 CPUs x86)

Scanning
1 file, 687205 bytes (672 KiB)


Unknown Error
```

v17.04 @ 4/04/21 is OK:

```
/mnt/dev1/dev/src/pak/7zip/p7zip/p7zip-17.04/bin $ ./7z  h 7z

7-Zip [32] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=pl_PL.utf8,Utf16=on,HugeFiles=on,32 bits,2 CPUs x86)

Scanning
1 file, 686680 bytes (671 KiB)

CRC32             Size  Name
-------- -------------  ------------
32808089        686680  7z
-------- -------------  ------------
32808089        686680  

Size: 686680

CRC32  for data:              32808089

Everything is Ok

```

**Comment by mshedsilegx** [comment]
I'm getting the same error with:
7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (306A9),ASM,AES-NI)

Same message: Unknown Error
It only affects CRC32, the other hashes are ok. (CRC64, SHA1, SHA256, SHA384, SHA512, XXH32, XXH64, BLAKE2sp, MD2, MD4, MD5)

**Comment by jinfeihan57** [comment]
Roll back to commit d64e1fdf7c2ee9ad67901225892badcdc1078f64.
and try again. Please.

**Comment by jinfeihan57** [comment]
Roll back to commit 91d7324ff508f28dcb5cb47777fb37b26272aa5d
and try again.

**Comment by mshedsilegx** [comment]
Confirmed fixed by compiling as of commit 91d7324
7z h computes CRC32 correctly.

**Comment by mshedsilegx** [comment]
d64e1fd is causing the regression. Re-compiling to this commit causes the error above for CRC32.

**Comment by jinfeihan57** [comment]
OK，I will fix this.
