### ISSUE TITLE
Zstandard is also part of zip format since 2020

### ISSUE THREAD

**Issue by stefano2734** [p7zip-project/p7zip#183]
See https://en.wikipedia.org/wiki/ZIP_(file_format)
with Pkzip format 6.3.8 available at 93 since 2020.

so my question here:
 is this supported in p7zip? 
 Or an older state of zip without zstandard?

**Comment by cielavenir** [comment]
you can use https://github.com/jinfeihan57/p7zip/releases/tag/v17.04 or https://github.com/cielavenir/p7zip/releases/tag/22.00.1 out of box

if you still want classic p7zip, extract cielavenir/p7zip/releases/tag/22.00.1 and copy Codecs directory to the same directory as 7z.so (note that this method only supports decompression)

**Comment by stefano2734** [comment]
I my opinion of a little user, it should be possible in the two ways zip-93 and zstd.
So the user has no problems with actual zip with zstd codec in zip-container.
And the user should can use normal zstd way.
That was my deeper intention.
That is than here  duplicate, but the world is not perfect.

Administrators can reduce with change to zstd inside the size of zip-files and more performance for user a lot without changing name of file. There is a great adavantage here on old zip area with zip93 possibility

Thanks for your great work.

**Comment by jinfeihan57** [comment]
Try this [branch](https://github.com/jinfeihan57/p7zip/tree/p7zip22.00).
