### ISSUE TITLE
arm64 NEON

### ISSUE THREAD

**Issue by woiza** [p7zip-project/p7zip#217]
Hi,

do you plan to use hardware CPU instructions for AES, CRC-32, SHA-1 and SHA-256 for arm64?

**Comment by tansy** [comment]
> Hi,
> 
> ... hardware CPU instructions for AES, CRC-32, SHA-1 and SHA-256 for arm64?

For that you better switch to 7zip-23.xx from sf.net. Pavlow works on it constantly.
With 17.xx noone does. Unless you plan to implement it yourself.

**Comment by woiza** [comment]
Thanks, will do.
