### ISSUE TITLE
Wrong version on latest release.

### ISSUE THREAD

**Issue by jinfeihan57** [p7zip-project/p7zip#218]
7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)
 should be 17.05

**Comment by flyfishzy** [comment]
Thanks @jinfeihan57 !
