### ISSUE TITLE
Retagging of version 17.05

### ISSUE THREAD

**Issue by FtZPetruska** [p7zip-project/p7zip#220]
Hello,

I wanted a confirmation that v17.05 was retagged from d5fa760eee206064ad037b177e1182eb86841094 to a45b8830cafda25e76d7120b0462daa82c382a7a.

Since yesterday, Homebrew users started having build failures due to hash mismatch on the `v17.05` tag. (see Homebrew/homebrew-core#124758)

Could a maintainer confirm that retagging was done on purpose ?

Thank you in advance!

**Comment by jinfeihan57** [comment]
Check this issue. #218
